---
- hosts: localhost
  connection: true
  become: true

  pre_tasks:
    - name: pre-run | update package cache
      apt:
        update_cache: yes

  tasks:
    - name: install packages
      package:
        state: latest
        name: 
          - neovim
          - zsh
          - stow

    - name: autoclean
      apt:
        autoclean: yes

    - name: autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes

    - name: download dotfiles
      git:
        repo: https://github.com/ben-hampson/dotfiles.git
        dest: /home/ben/dotfiles/
        clone: yes
        update: yes

    - name: stow dotfiles
      command: stow .
      args:
        chdir: /home/ben/dotfiles/

