---
- hosts: localhost
  connection: true
  become: true

  pre_tasks:
    - name: pre-run | update package cache
      apt:
        update_cache: yes

  tasks:
    - name: install packages
      package:
        state: latest
        name: 
          - neovim
          - zsh
          - stow
          - wget
          - unzip

    - name: autoclean
      apt:
        autoclean: yes

    - name: autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes

    - name: download dotfiles
      git:
        repo: https://github.com/ben-hampson/dotfiles.git
        dest: /home/ben/dotfiles/
        clone: yes
        update: yes

    - name: download zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes
          
    - name: download zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes
          
    - name: download powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes
        update: yes

    - name: stow dotfiles
      command: stow .
      args:
        chdir: /home/ben/dotfiles/

    - name: Create JetBrains Mono Nerd Font dir
      file:
        path: /home/ben/JetBrainsMono
        state: directory

    - name: Create ~/.fonts
      file:
        path: /home/ben/.fonts
        state: directory

    - name: unzip jetbrains mono nerd font
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
        dest: /home/ben/JetBrainsMono
        creates: /home/ben/JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf 
        remote_src: yes

    - name: install jetbrains mono nerd font
      args:
        chdir: /home/ben
      shell: |
        cp JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf .fonts/
        fc-cache -fv

    - name: snap install neovim
      community.general.snap:
        name: nvim
        classic: true

