---
- hosts: localhost
  connection: true
  become: true
  vars:
      keyring_url: "https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2023.02.18_all.deb"
      keyring_path: "/tmp/keyring.deb"
      keyring_checksum: "sha256:a511ac5f10cd811f8a4ca44d665f2fa1add7a9f09bef238cdfad8461f5239cc4"

  pre_tasks:
    - name: pre-run | update package cache
      apt:
        update_cache: yes

  tasks:
    - name: apt install packages
      package:
        state: latest
        name: 
          - neovim
          - zsh
          - stow
          - wget
          - unzip
          - i3
          - ripgrep
          - polybar
          - feh

    - name: snap install apps
      community.general.snap:
        name: 
          - nvim
          - alacritty
          - firefox
        classic: true

    - name: autoclean
      apt:
        autoclean: yes

    - name: autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes

    - name: download dotfiles
      git:
        repo: https://github.com/ben-hampson/dotfiles.git
        version: ubuntu2204server
        dest: /home/ben/dotfiles/
        force: yes
        clone: yes
        update: yes

    - name: download zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes
          
    - name: download zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes
          
    - name: download powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes
        update: yes

    - name: stow dotfiles
      command: stow .
      args:
        chdir: /home/ben/dotfiles/

    - name: Create JetBrains Mono Nerd Font dir
      file:
        path: /home/ben/JetBrainsMono
        state: directory

    - name: Create ~/.fonts
      file:
        path: /home/ben/.fonts
        state: directory

    - name: unzip jetbrains mono nerd font
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
        dest: /home/ben/JetBrainsMono
        creates: /home/ben/JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf 
        remote_src: yes

    - name: install jetbrains mono nerd font
      args:
        chdir: /home/ben
      shell: |
        cp JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf .fonts/
        fc-cache -fv

    - name: Download the sur5r keyring package
      ansible.builtin.get_url:
        url: "{{ keyring_url }}"
        dest: "{{ keyring_path }}"
        checksum: "{{ keyring_checksum }}"

    - name: Install the sur5r keyring package
      ansible.builtin.apt:
        deb: "{{ keyring_path }}"

    - name: Add the i3wm repository
      ansible.builtin.apt_repository:
        repo: "deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
        filename: 'sur5r-i3'
        state: present
        update_cache: yes

    - name: Install i3 window manager
      ansible.builtin.apt:
        name: i3
        state: latest
        update_cache: yes
