---
- hosts: localhost
  connection: true
  become: true

  pre_tasks:
    - name: pre-run | update package cache
      apt:
        update_cache: yes

  tasks:
    - name: apt install packages
      package:
        state: latest
        name: 
          - zsh
          - stow
          - wget
          - unzip
          - ripgrep
          - polybar
          - feh
          - rofi

    - name: add apt repo for alacritty
      ansible.builtin.apt_repository:
        repo: 'ppa:aslatter/ppa'
        state: present
        codename: jammy

    - name: apt install alacritty
      package:
        state: latest
        name: alacritty
        update_cache: yes

    - name: Set shell to zsh
      ansible.builtin.user:
        name: ben
        shell: /bin/zsh

    - name: autoclean
      apt:
        autoclean: yes

    - name: autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes

    - name: Download dotfiles
      git:
        repo: https://github.com/ben-hampson/dotfiles.git
        version: ubuntu2204server
        dest: /home/ben/dotfiles/
        force: yes
        clone: yes
        update: yes

    - name: Download zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: yes
        update: yes
          
    - name: Download zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes
          
    - name: Download powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/ben/dotfiles/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes
        update: yes

    - name: set ownership of dotfiles
      file:
        path: /home/ben/dotfiles
        owner: ben
        recurse: true

    - name: stow dotfiles
      command: stow .
      args:
        chdir: /home/ben/dotfiles/

    - name: Create JetBrains Mono Nerd Font dir
      file:
        path: /home/ben/JetBrainsMono
        state: directory

    - name: Create ~/.fonts
      file:
        path: /home/ben/.fonts
        state: directory

    - name: Unzip jetbrains mono nerd font
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
        dest: /home/ben/JetBrainsMono
        creates: /home/ben/JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf 
        remote_src: yes

    - name: Install jetbrains mono nerd font
      args:
        chdir: /home/ben
      shell: |
        cp JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf .fonts/
        fc-cache -fv

    - name: Create ~/.local/bin
      file:
        path: /home/ben/.local/bin
        state: directory
        owner: ben
        recurse: true
      tags:
        - nvim

    - name: Install neovim
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        dest: /usr/bin/nvim
        mode: 0755
        owner: ben
      tags:
        - nvim

    - name: Download i3 keyring.deb
      get_url:
        url: "https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb"
        dest: "/tmp/i3-keyring.deb"
        checksum: "sha256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734"
        mode: '0644'
      tags:
        - i3

    - name: Install i3 keyring.deb
      apt:
        deb: "/tmp/i3-keyring.deb"
      tags:
        - i3
        
    - name: Add i3 apt repository
      ansible.builtin.apt_repository:
        repo: deb http://debian.sur5r.net/i3/ virginia universe
        filename: sur5r-i3
      tags:
        - i3

    - name: apt install i3
      ansible.builtin.package:
        name: i3
        update_cache: true
      tags:
        - i3

    - name: asdf and Python
      tags:
        - python
      block: 
        - name: Download asdf
          git:
            repo: https://github.com/asdf-vm/asdf.git
            version: v0.14.0
            dest: /home/ben/.asdf
            force: yes
            clone: yes
            update: yes

        - name: Set ownership for ~/.asdf
          file:
            path: /home/ben/.asdf
            owner: ben
            recurse: true

        - name: Download asdf plugin for oh-my-zsh
          git:
            repo: https://github.com/asdf-vm/asdf.git
            dest: /home/ben/.asdf
          tags:
            - asdf
            
        - name: Install requirements for python and asdf
          package:
            state: latest
            name:
              - build-essential
              - libssl-dev
              - zlib1g-dev
              - libbz2-dev
              - libreadline-dev
              - libsqlite3-dev
              - wget
              - llvm
              - libncursesw5-dev
              - xz-utils
              - tk-dev
              - libxml2-dev
              - libxmlsec1-dev
              - libffi-dev
              - liblzma-dev

        - name: Install asdf python plugin
          command: asdf plugin add python

        - name: Install python 3.8 and 3.11
          command:
            - asdf install python latest:3.8
            - asdf install python latest:3.11

    - name: Poetry
      tags:
        - poetry
      block:
        - name: Download script to install poetry
          get_url:
            url: https://install.python-poetry.org
            dest: /tmp/poetry-install.py
            mode: 0755
            owner: ben

        - name: Install poetry
          command: python /tmp/poetry-install.py

